services:
  - type: web
    name: ScrapeSquad
    env: node
    buildCommand: |
      # Update and install dependencies
      apt-get update && \
      apt-get install -y wget gnupg ca-certificates

      # Add Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

      # Install Chrome
      apt-get update && \
      apt-get install -y google-chrome-stable

      # Install Node dependencies
      npm install
      
      # Build client
      cd client && npm install
      cd client && npm run build

      # Install Node dependencies
      npm install
      
      # Install Playwright with system dependencies
      PLAYWRIGHT_SKIP_BROWSER_GC=1 npx playwright install-deps chromium
      PLAYWRIGHT_SKIP_BROWSER_GC=1 npx playwright install chromium
      
      # Build client
      cd client && npm install
      cd client && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROME_PATH
        value: "/usr/bin/google-chrome"
      - key: PLAYWRIGHT_SKIP_BROWSER_GC
        value: "1"
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: /opt/render/.playwright/chromium-1097/chrome-linux/chrome
